
services:
  postgres:
    image: postgres:15
    container_name: playersto1k_postgres
    environment:
      POSTGRES_DB: football
      POSTGRES_USER: aalex
      POSTGRES_PASSWORD: aalex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

