-- CreateTable
CREATE TABLE "PlayerFixtureStatistic" (
    "playerId" INTEGER NOT NULL,
    "fixtureId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "games_minutes" INTEGER NOT NULL,
    "games_number" INTEGER NOT NULL,
    "games_position" TEXT NOT NULL,
    "games_rating" TEXT NOT NULL,
    "games_captain" BOOLEAN NOT NULL,
    "games_substitute" BOOLEAN NOT NULL,
    "offsides" INTEGER NOT NULL,
    "shots_total" INTEGER NOT NULL,
    "shots_on" INTEGER NOT NULL,
    "goals_total" INTEGER,
    "goals_conceded" INTEGER NOT NULL,
    "goals_assists" INTEGER NOT NULL,
    "goals_saves" INTEGER,
    "passes_total" INTEGER NOT NULL,
    "passes_key" INTEGER NOT NULL,
    "passes_accuracy" TEXT NOT NULL,
    "tackles_total" INTEGER,
    "tackles_blocks" INTEGER,
    "tackles_interceptions" INTEGER,
    "duels_total" INTEGER NOT NULL,
    "duels_won" INTEGER NOT NULL,
    "dribbles_attempts" INTEGER NOT NULL,
    "dribbles_success" INTEGER NOT NULL,
    "dribbles_past" INTEGER,
    "fouls_drawn" INTEGER,
    "fouls_committed" INTEGER,
    "cards_yellow" INTEGER NOT NULL,
    "cards_red" INTEGER NOT NULL,
    "penalty_won" INTEGER,
    "penalty_commited" INTEGER,
    "penalty_scored" INTEGER NOT NULL,
    "penalty_missed" INTEGER NOT NULL,
    "penalty_saved" INTEGER,

    CONSTRAINT "PlayerFixtureStatistic_pkey" PRIMARY KEY ("playerId","fixtureId")
);
